# Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]]).T

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis=0)

In [5]:
mean_a

array([2. , 8.4])

#  Задание 2

In [6]:
a_centered = a - mean_a

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [8]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [9]:
a_centered_sp

8.0

In [10]:
a_cov = a_centered_sp / (len(a) - 1)

In [11]:
a_cov

2.0